# Generated by Django 3.2.7 on 2021-11-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctname', models.CharField(default='', max_length=30)),
                ('ctemail', models.EmailField(default='', max_length=20)),
                ('ctsubject', models.CharField(default='', max_length=30)),
                ('ctmessage', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='studentgriev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('contactnum', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=20)),
                ('grievance', models.TextField(default='')),
                ('entered_on', models.DateTimeField(auto_now_add=True)),
                ('is_solved', models.BooleanField()),
            ],
        ),
    ]
