# Generated by Django 3.2.7 on 2021-11-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgrc', '0006_remove_studentgriev_is_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgriev',
            name='status',
            field=models.CharField(choices=[('Solved', 'SL'), ('Pending', 'PN'), ('Not Solved', 'NSL')], default='', max_length=100),
        ),
    ]
