# Generated by Django 3.2.7 on 2021-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgrc', '0007_alter_studentgriev_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgriev',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending'), ('Not Solved', 'Not Solved')], default='', max_length=100),
        ),
    ]
