# Generated by Django 3.2.7 on 2021-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgrc', '0008_alter_studentgriev_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='facgrieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(default='')),
            ],
        ),
    ]
