# Generated by Django 3.2.7 on 2021-11-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgrc', '0014_alter_studentgriev_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgriev',
            name='user',
        ),
    ]
